# --- Sample dataset

# --- !Ups

insert into make values(1,'Abarth');
insert into make values(2,'Ac');
insert into make values(3,'Acura');
insert into make values(4,'Alfa Romeo');
insert into make values(5,'Allard');
insert into make values(6,'Alpina');
insert into make values(7,'Alpine');
insert into make values(8,'Alvis');
insert into make values(9,'Amc');
insert into make values(10,'Ariel');
insert into make values(11,'Armstrong Siddeley');
insert into make values(12,'Ascari');
insert into make values(13,'Aston Martin');
insert into make values(14,'Audi');
insert into make values(15,'Austin');
insert into make values(16,'Austin Healey');
insert into make values(17,'Autobianchi');
insert into make values(18,'Auverland');
insert into make values(19,'Avanti');
insert into make values(20,'Beijing');
insert into make values(21,'Bentley');
insert into make values(22,'Berkeley');
insert into make values(23,'Bitter');
insert into make values(24,'Bizzarrini');
insert into make values(25,'Bmw');
insert into make values(26,'Brilliance');
insert into make values(27,'Bristol');
insert into make values(28,'Bugatti');
insert into make values(29,'Buick');
insert into make values(30,'Cadillac');
insert into make values(31,'Caterham');
insert into make values(32,'Checker');
insert into make values(33,'Chevrolet');
insert into make values(34,'Chrysler');
insert into make values(35,'Citroen');
insert into make values(36,'Dacia');
insert into make values(37,'Daewoo');
insert into make values(38,'Daf');
insert into make values(39,'Daihatsu');
insert into make values(40,'Daimler');
insert into make values(41,'Datsun');
insert into make values(42,'De Tomaso');
insert into make values(43,'Dkw');
insert into make values(44,'Dodge');
insert into make values(45,'Donkervoort');
insert into make values(46,'Eagle');
insert into make values(47,'Fairthorpe');
insert into make values(48,'Ferrari');
insert into make values(49,'Fiat');
insert into make values(50,'Fisker');
insert into make values(51,'Ford');
insert into make values(52,'Gaz');
insert into make values(53,'Geely');
insert into make values(54,'Ginetta');
insert into make values(55,'Gmc');
insert into make values(56,'Holden');
insert into make values(57,'Honda');
insert into make values(58,'Hudson');
insert into make values(59,'Humber');
insert into make values(60,'Hummer');
insert into make values(61,'Hyundai');
insert into make values(62,'Infiniti');
insert into make values(63,'Innocenti');
insert into make values(64,'Isuzu');
insert into make values(65,'Italdesign');
insert into make values(66,'Jaguar');
insert into make values(67,'Jeep');
insert into make values(68,'Jensen');
insert into make values(69,'Kia');
insert into make values(70,'Koenigsegg');
insert into make values(71,'Lada');
insert into make values(72,'Lamborghini');
insert into make values(73,'Lancia');
insert into make values(74,'Land Rover');
insert into make values(75,'Lexus');
insert into make values(76,'Lincoln');
insert into make values(77,'Lotec');
insert into make values(78,'Lotus');
insert into make values(79,'Luxgen');
insert into make values(80,'Mahindra');
insert into make values(81,'Marcos');
insert into make values(82,'Maserati');
insert into make values(83,'Matra Simca');
insert into make values(84,'Maybach');
insert into make values(85,'Mazda');
insert into make values(86,'Mcc');
insert into make values(87,'Mclaren');
insert into make values(88,'Mercedes Benz');
insert into make values(89,'Mercury');
insert into make values(90,'Mg');
insert into make values(91,'Mini');
insert into make values(92,'Mitsubishi');
insert into make values(93,'Monteverdi');
insert into make values(94,'Moretti');
insert into make values(95,'Morgan');
insert into make values(96,'Morris');
insert into make values(97,'Nissan');
insert into make values(98,'Noble');
insert into make values(99,'Nsu');
insert into make values(100,'Oldsmobile');
insert into make values(101,'Opel');
insert into make values(102,'Packard');
insert into make values(103,'Pagani');
insert into make values(104,'Panoz');
insert into make values(105,'Peugeot');
insert into make values(106,'Pininfarina');
insert into make values(107,'Plymouth');
insert into make values(108,'Pontiac');
insert into make values(109,'Porsche');
insert into make values(110,'Proton');
insert into make values(111,'Reliant');
insert into make values(112,'Renault');
insert into make values(113,'Riley');
insert into make values(114,'Rolls Royce');
insert into make values(115,'Rover');
insert into make values(116,'Saab');
insert into make values(117,'Saleen');
insert into make values(118,'Samsung');
insert into make values(119,'Saturn');
insert into make values(120,'Scion');
insert into make values(121,'Seat');
insert into make values(122,'Simca');
insert into make values(123,'Singer');
insert into make values(124,'Skoda');
insert into make values(125,'Smart');
insert into make values(126,'Spyker');
insert into make values(127,'Ssangyong');
insert into make values(128,'Ssc');
insert into make values(129,'Steyr');
insert into make values(130,'Studebaker');
insert into make values(131,'Subaru');
insert into make values(132,'Sunbeam');
insert into make values(133,'Suzuki');
insert into make values(134,'Talbot');
insert into make values(135,'Tata');
insert into make values(136,'Tatra');
insert into make values(137,'Tesla');
insert into make values(138,'Toyota');
insert into make values(139,'Trabant');
insert into make values(140,'Triumph');
insert into make values(141,'Tvr');
insert into make values(142,'Vauxhall');
insert into make values(143,'Vector');
insert into make values(144,'Venturi');
insert into make values(145,'Volkswagen');
insert into make values(146,'Volvo');
insert into make values(147,'Wartburg');
insert into make values(148,'Westfield');
insert into make values(149,'Willys Overland');
insert into make values(150,'Xedos');
insert into make values(151,'Zagato');
insert into make values(152,'Zastava');
insert into make values(153,'Zaz');
insert into make values(154,'Zenvo');
insert into make values(155,'Zil');

# --- !Downs

delete from make;
